name: pangenome
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconda::fasttree=2.1.11
  - bioconda::iqtree=2.1.2
  - bioconda::prokka=1.14.6
  - bioconda::roary=3.13.0
  - bioconda::r-ggplot2=3.3.5
  - bioconda::r-optparse=1.7.1
  - bioconda::r-tidyr=1.2.0
  - bioconda::mafft=7.407
  - bioconda::trimal=1.4.1
  - bioconda::diamond=0.9.25
